### ISSUE TITLE
Como utilizar?

### ISSUE THREAD

**Issue by nykolaslima** [lucasaraujo/swagger-vraptor-maven-plugin#1]
@lucasaraujo voce ainda utiliza esse projeto? Sabe se ele funciona com VRaptor4?

**Comment by lucasaraujo** [comment]
Não testei no vraptor 4 mas acredito que deve funcionar.

Para usar é necessário adicionar as anotações do swagger-annotations nas classes e métodos.
A dependencia é:

``` xml
<dependency>
    <groupId>com.wordnik</groupId>
    <artifactId>swagger-annotations</artifactId>
    <version>1.3.2</version>
</dependency>
```

Exemplo das anotações:

``` java
@com.wordnik.swagger.annotations.Api(value = "Contacts")
public class ContactsController {

    @br.com.caelum.vraptor.Get("/contacts")
    @com.wordnik.swagger.annotations.ApiOperation(value = "List current user contacts", response = Contact.class)
    public void contacts() {
        // ...
    }
}
```

O plugin não esta no repositório central, então é preciso clonar e projeto e instalar no repositório local (`mvn install`).
Depois basta configurar em que fase e onde serão gerados os arquivos, adicionando no pom.xml:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <!-- ... -->
    <build>
        <!-- ... -->
        <plugins>
            <!-- ... -->
            <plugin>
                <groupId>com.github.lucasaraujo</groupId>
                <artifactId>swagger-vraptor-maven-plugin</artifactId>
                <version>0.1-SNAPSHOT</version>
                <configuration>
                    <!-- Versão da API -->
                    <apiVersion>1.0.0</apiVersion>
                    <!-- Usar para gerar as URLs em algum contexto (prefixo) -->
                    <basePath>/</basePath>
                    <locations>
                        <!-- Listar o(s) pacote(s) onde buscar as anotações -->
                        <param>org.company.controller</param>
                    </locations>
                    <!-- local onde os arquivos serão salvos -->
                    <swaggerDirectory>${basedir}/src/main/webapp/api-docs</swaggerDirectory>
                </configuration>
                <executions>
                    <execution>
                        <!-- configurar quando os arquivos serão gerados -->
                        <phase>process-classes</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <!-- ... -->
        </plugins>
        <!-- ... -->
    </build>
    <!-- ... -->
</project>
```

**Comment by flaviociaware** [comment]
Estamos tentando usar mas ele dá erro com o process-classes e o generate. A consequência é que não gera o api-docs.

Qdo usamos a configuração que está descrita aqui e no README.md obtivemos este erro:
Plugin execution not covered by lifecycle configuration: com.github.lucasaraujo:swagger-vraptor-maven-plugin:0.1-SNAPSHOT:generate (execution: default, phase: process-classes)

**Comment by Turini** [comment]
@nykolaslima você chegou a usar esse plugin com VRaptor 4?

**Comment by flaviociaware** [comment]
Sim, tentamos com VRaptor 4.

**Comment by carlosspohr** [comment]
Buenas, 

Como que contorna esse problema do 'process-classes' quando eu adiciono esse plugin?

Estou um tempo aqui tentando fazer ele funcionar. @flaviociaware, você conseguiu fazer ele rodar no seu projeto aí ?

**Comment by flaviociaware** [comment]
Pausamos essa parte Carlos.

[]'s

2016-05-08 23:28 GMT-03:00 Carlos Alberto Junior Spohr Poletto <
notifications@github.com>:

> Buenas,
> 
> Como que contorna esse problema do 'process-classes' quando eu adiciono
> esse plugin?
> 
> Estou um tempo aqui tentando fazer ele funcionar. @flaviociaware
> https://github.com/flaviociaware, você conseguiu fazer ele rodar no seu
> projeto aí ?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/lucasaraujo/swagger-vraptor-maven-plugin/issues/1#issuecomment-217764067

## 

[]´s Dr. Flavio Barbosa
E-Mail: flavio@ciaware.com.br
Facebook: https://www.facebook.com/CIAware
